//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace PoliceSMS.SMSRecordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSRecordService.ISMSRecordService")]
    public interface ISMSRecordService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/SaveOrUpdate", ReplyAction="http://tempuri.org/ISMSRecordService/SaveOrUpdateResponse")]
        System.IAsyncResult BeginSaveOrUpdate(string json, System.AsyncCallback callback, object asyncState);
        
        string EndSaveOrUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/SaveList", ReplyAction="http://tempuri.org/ISMSRecordService/SaveListResponse")]
        System.IAsyncResult BeginSaveList(string json, int cnt, System.AsyncCallback callback, object asyncState);
        
        string EndSaveList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/DeleteById", ReplyAction="http://tempuri.org/ISMSRecordService/DeleteByIdResponse")]
        System.IAsyncResult BeginDeleteById(int id, System.AsyncCallback callback, object asyncState);
        
        string EndDeleteById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/GetById", ReplyAction="http://tempuri.org/ISMSRecordService/GetByIdResponse")]
        System.IAsyncResult BeginGetById(int id, System.AsyncCallback callback, object asyncState);
        
        string EndGetById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/GetByHql", ReplyAction="http://tempuri.org/ISMSRecordService/GetByHqlResponse")]
        System.IAsyncResult BeginGetByHql(string hql, System.AsyncCallback callback, object asyncState);
        
        string EndGetByHql(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/GetListByHQL", ReplyAction="http://tempuri.org/ISMSRecordService/GetListByHQLResponse")]
        System.IAsyncResult BeginGetListByHQL(string hqlQuery, System.AsyncCallback callback, object asyncState);
        
        string EndGetListByHQL(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/GetListBySQL", ReplyAction="http://tempuri.org/ISMSRecordService/GetListBySQLResponse")]
        System.IAsyncResult BeginGetListBySQL(string sql, System.AsyncCallback callback, object asyncState);
        
        string EndGetListBySQL(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/GetListByHQLWithPaging", ReplyAction="http://tempuri.org/ISMSRecordService/GetListByHQLWithPagingResponse")]
        System.IAsyncResult BeginGetListByHQLWithPaging(string query, System.AsyncCallback callback, object asyncState);
        
        string EndGetListByHQLWithPaging(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/GetListByProperties", ReplyAction="http://tempuri.org/ISMSRecordService/GetListByPropertiesResponse")]
        System.IAsyncResult BeginGetListByProperties(string properties, System.AsyncCallback callback, object asyncState);
        
        string EndGetListByProperties(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISMSRecordService/Export", ReplyAction="http://tempuri.org/ISMSRecordService/ExportResponse")]
        System.IAsyncResult BeginExport(string query, System.AsyncCallback callback, object asyncState);
        
        string EndExport(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSRecordServiceChannel : PoliceSMS.SMSRecordService.ISMSRecordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveOrUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveOrUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByHqlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByHqlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListByHQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListByHQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListBySQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListBySQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListByHQLWithPagingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListByHQLWithPagingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListByPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListByPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSRecordServiceClient : System.ServiceModel.ClientBase<PoliceSMS.SMSRecordService.ISMSRecordService>, PoliceSMS.SMSRecordService.ISMSRecordService {
        
        private BeginOperationDelegate onBeginSaveOrUpdateDelegate;
        
        private EndOperationDelegate onEndSaveOrUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onSaveOrUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveListDelegate;
        
        private EndOperationDelegate onEndSaveListDelegate;
        
        private System.Threading.SendOrPostCallback onSaveListCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteByIdDelegate;
        
        private EndOperationDelegate onEndDeleteByIdDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByIdDelegate;
        
        private EndOperationDelegate onEndGetByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByHqlDelegate;
        
        private EndOperationDelegate onEndGetByHqlDelegate;
        
        private System.Threading.SendOrPostCallback onGetByHqlCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetListByHQLDelegate;
        
        private EndOperationDelegate onEndGetListByHQLDelegate;
        
        private System.Threading.SendOrPostCallback onGetListByHQLCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetListBySQLDelegate;
        
        private EndOperationDelegate onEndGetListBySQLDelegate;
        
        private System.Threading.SendOrPostCallback onGetListBySQLCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetListByHQLWithPagingDelegate;
        
        private EndOperationDelegate onEndGetListByHQLWithPagingDelegate;
        
        private System.Threading.SendOrPostCallback onGetListByHQLWithPagingCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetListByPropertiesDelegate;
        
        private EndOperationDelegate onEndGetListByPropertiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetListByPropertiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginExportDelegate;
        
        private EndOperationDelegate onEndExportDelegate;
        
        private System.Threading.SendOrPostCallback onExportCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SMSRecordServiceClient() {
        }
        
        public SMSRecordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSRecordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSRecordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSRecordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SaveOrUpdateCompletedEventArgs> SaveOrUpdateCompleted;
        
        public event System.EventHandler<SaveListCompletedEventArgs> SaveListCompleted;
        
        public event System.EventHandler<DeleteByIdCompletedEventArgs> DeleteByIdCompleted;
        
        public event System.EventHandler<GetByIdCompletedEventArgs> GetByIdCompleted;
        
        public event System.EventHandler<GetByHqlCompletedEventArgs> GetByHqlCompleted;
        
        public event System.EventHandler<GetListByHQLCompletedEventArgs> GetListByHQLCompleted;
        
        public event System.EventHandler<GetListBySQLCompletedEventArgs> GetListBySQLCompleted;
        
        public event System.EventHandler<GetListByHQLWithPagingCompletedEventArgs> GetListByHQLWithPagingCompleted;
        
        public event System.EventHandler<GetListByPropertiesCompletedEventArgs> GetListByPropertiesCompleted;
        
        public event System.EventHandler<ExportCompletedEventArgs> ExportCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginSaveOrUpdate(string json, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveOrUpdate(json, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndSaveOrUpdate(System.IAsyncResult result) {
            return base.Channel.EndSaveOrUpdate(result);
        }
        
        private System.IAsyncResult OnBeginSaveOrUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string json = ((string)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginSaveOrUpdate(json, callback, asyncState);
        }
        
        private object[] OnEndSaveOrUpdate(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndSaveOrUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveOrUpdateCompleted(object state) {
            if ((this.SaveOrUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveOrUpdateCompleted(this, new SaveOrUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveOrUpdateAsync(string json) {
            this.SaveOrUpdateAsync(json, null);
        }
        
        public void SaveOrUpdateAsync(string json, object userState) {
            if ((this.onBeginSaveOrUpdateDelegate == null)) {
                this.onBeginSaveOrUpdateDelegate = new BeginOperationDelegate(this.OnBeginSaveOrUpdate);
            }
            if ((this.onEndSaveOrUpdateDelegate == null)) {
                this.onEndSaveOrUpdateDelegate = new EndOperationDelegate(this.OnEndSaveOrUpdate);
            }
            if ((this.onSaveOrUpdateCompletedDelegate == null)) {
                this.onSaveOrUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveOrUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginSaveOrUpdateDelegate, new object[] {
                        json}, this.onEndSaveOrUpdateDelegate, this.onSaveOrUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginSaveList(string json, int cnt, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveList(json, cnt, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndSaveList(System.IAsyncResult result) {
            return base.Channel.EndSaveList(result);
        }
        
        private System.IAsyncResult OnBeginSaveList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string json = ((string)(inValues[0]));
            int cnt = ((int)(inValues[1]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginSaveList(json, cnt, callback, asyncState);
        }
        
        private object[] OnEndSaveList(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndSaveList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveListCompleted(object state) {
            if ((this.SaveListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveListCompleted(this, new SaveListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveListAsync(string json, int cnt) {
            this.SaveListAsync(json, cnt, null);
        }
        
        public void SaveListAsync(string json, int cnt, object userState) {
            if ((this.onBeginSaveListDelegate == null)) {
                this.onBeginSaveListDelegate = new BeginOperationDelegate(this.OnBeginSaveList);
            }
            if ((this.onEndSaveListDelegate == null)) {
                this.onEndSaveListDelegate = new EndOperationDelegate(this.OnEndSaveList);
            }
            if ((this.onSaveListCompletedDelegate == null)) {
                this.onSaveListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveListCompleted);
            }
            base.InvokeAsync(this.onBeginSaveListDelegate, new object[] {
                        json,
                        cnt}, this.onEndSaveListDelegate, this.onSaveListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginDeleteById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndDeleteById(System.IAsyncResult result) {
            return base.Channel.EndDeleteById(result);
        }
        
        private System.IAsyncResult OnBeginDeleteById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginDeleteById(id, callback, asyncState);
        }
        
        private object[] OnEndDeleteById(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndDeleteById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteByIdCompleted(object state) {
            if ((this.DeleteByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteByIdCompleted(this, new DeleteByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteByIdAsync(int id) {
            this.DeleteByIdAsync(id, null);
        }
        
        public void DeleteByIdAsync(int id, object userState) {
            if ((this.onBeginDeleteByIdDelegate == null)) {
                this.onBeginDeleteByIdDelegate = new BeginOperationDelegate(this.OnBeginDeleteById);
            }
            if ((this.onEndDeleteByIdDelegate == null)) {
                this.onEndDeleteByIdDelegate = new EndOperationDelegate(this.OnEndDeleteById);
            }
            if ((this.onDeleteByIdCompletedDelegate == null)) {
                this.onDeleteByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteByIdCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteByIdDelegate, new object[] {
                        id}, this.onEndDeleteByIdDelegate, this.onDeleteByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginGetById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndGetById(System.IAsyncResult result) {
            return base.Channel.EndGetById(result);
        }
        
        private System.IAsyncResult OnBeginGetById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginGetById(id, callback, asyncState);
        }
        
        private object[] OnEndGetById(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndGetById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByIdCompleted(object state) {
            if ((this.GetByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByIdAsync(int id) {
            this.GetByIdAsync(id, null);
        }
        
        public void GetByIdAsync(int id, object userState) {
            if ((this.onBeginGetByIdDelegate == null)) {
                this.onBeginGetByIdDelegate = new BeginOperationDelegate(this.OnBeginGetById);
            }
            if ((this.onEndGetByIdDelegate == null)) {
                this.onEndGetByIdDelegate = new EndOperationDelegate(this.OnEndGetById);
            }
            if ((this.onGetByIdCompletedDelegate == null)) {
                this.onGetByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetByIdDelegate, new object[] {
                        id}, this.onEndGetByIdDelegate, this.onGetByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginGetByHql(string hql, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByHql(hql, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndGetByHql(System.IAsyncResult result) {
            return base.Channel.EndGetByHql(result);
        }
        
        private System.IAsyncResult OnBeginGetByHql(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string hql = ((string)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginGetByHql(hql, callback, asyncState);
        }
        
        private object[] OnEndGetByHql(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndGetByHql(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByHqlCompleted(object state) {
            if ((this.GetByHqlCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByHqlCompleted(this, new GetByHqlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByHqlAsync(string hql) {
            this.GetByHqlAsync(hql, null);
        }
        
        public void GetByHqlAsync(string hql, object userState) {
            if ((this.onBeginGetByHqlDelegate == null)) {
                this.onBeginGetByHqlDelegate = new BeginOperationDelegate(this.OnBeginGetByHql);
            }
            if ((this.onEndGetByHqlDelegate == null)) {
                this.onEndGetByHqlDelegate = new EndOperationDelegate(this.OnEndGetByHql);
            }
            if ((this.onGetByHqlCompletedDelegate == null)) {
                this.onGetByHqlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByHqlCompleted);
            }
            base.InvokeAsync(this.onBeginGetByHqlDelegate, new object[] {
                        hql}, this.onEndGetByHqlDelegate, this.onGetByHqlCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginGetListByHQL(string hqlQuery, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListByHQL(hqlQuery, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndGetListByHQL(System.IAsyncResult result) {
            return base.Channel.EndGetListByHQL(result);
        }
        
        private System.IAsyncResult OnBeginGetListByHQL(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string hqlQuery = ((string)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginGetListByHQL(hqlQuery, callback, asyncState);
        }
        
        private object[] OnEndGetListByHQL(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndGetListByHQL(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListByHQLCompleted(object state) {
            if ((this.GetListByHQLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListByHQLCompleted(this, new GetListByHQLCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListByHQLAsync(string hqlQuery) {
            this.GetListByHQLAsync(hqlQuery, null);
        }
        
        public void GetListByHQLAsync(string hqlQuery, object userState) {
            if ((this.onBeginGetListByHQLDelegate == null)) {
                this.onBeginGetListByHQLDelegate = new BeginOperationDelegate(this.OnBeginGetListByHQL);
            }
            if ((this.onEndGetListByHQLDelegate == null)) {
                this.onEndGetListByHQLDelegate = new EndOperationDelegate(this.OnEndGetListByHQL);
            }
            if ((this.onGetListByHQLCompletedDelegate == null)) {
                this.onGetListByHQLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListByHQLCompleted);
            }
            base.InvokeAsync(this.onBeginGetListByHQLDelegate, new object[] {
                        hqlQuery}, this.onEndGetListByHQLDelegate, this.onGetListByHQLCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginGetListBySQL(string sql, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListBySQL(sql, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndGetListBySQL(System.IAsyncResult result) {
            return base.Channel.EndGetListBySQL(result);
        }
        
        private System.IAsyncResult OnBeginGetListBySQL(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sql = ((string)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginGetListBySQL(sql, callback, asyncState);
        }
        
        private object[] OnEndGetListBySQL(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndGetListBySQL(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListBySQLCompleted(object state) {
            if ((this.GetListBySQLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListBySQLCompleted(this, new GetListBySQLCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListBySQLAsync(string sql) {
            this.GetListBySQLAsync(sql, null);
        }
        
        public void GetListBySQLAsync(string sql, object userState) {
            if ((this.onBeginGetListBySQLDelegate == null)) {
                this.onBeginGetListBySQLDelegate = new BeginOperationDelegate(this.OnBeginGetListBySQL);
            }
            if ((this.onEndGetListBySQLDelegate == null)) {
                this.onEndGetListBySQLDelegate = new EndOperationDelegate(this.OnEndGetListBySQL);
            }
            if ((this.onGetListBySQLCompletedDelegate == null)) {
                this.onGetListBySQLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListBySQLCompleted);
            }
            base.InvokeAsync(this.onBeginGetListBySQLDelegate, new object[] {
                        sql}, this.onEndGetListBySQLDelegate, this.onGetListBySQLCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginGetListByHQLWithPaging(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListByHQLWithPaging(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndGetListByHQLWithPaging(System.IAsyncResult result) {
            return base.Channel.EndGetListByHQLWithPaging(result);
        }
        
        private System.IAsyncResult OnBeginGetListByHQLWithPaging(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginGetListByHQLWithPaging(query, callback, asyncState);
        }
        
        private object[] OnEndGetListByHQLWithPaging(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndGetListByHQLWithPaging(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListByHQLWithPagingCompleted(object state) {
            if ((this.GetListByHQLWithPagingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListByHQLWithPagingCompleted(this, new GetListByHQLWithPagingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListByHQLWithPagingAsync(string query) {
            this.GetListByHQLWithPagingAsync(query, null);
        }
        
        public void GetListByHQLWithPagingAsync(string query, object userState) {
            if ((this.onBeginGetListByHQLWithPagingDelegate == null)) {
                this.onBeginGetListByHQLWithPagingDelegate = new BeginOperationDelegate(this.OnBeginGetListByHQLWithPaging);
            }
            if ((this.onEndGetListByHQLWithPagingDelegate == null)) {
                this.onEndGetListByHQLWithPagingDelegate = new EndOperationDelegate(this.OnEndGetListByHQLWithPaging);
            }
            if ((this.onGetListByHQLWithPagingCompletedDelegate == null)) {
                this.onGetListByHQLWithPagingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListByHQLWithPagingCompleted);
            }
            base.InvokeAsync(this.onBeginGetListByHQLWithPagingDelegate, new object[] {
                        query}, this.onEndGetListByHQLWithPagingDelegate, this.onGetListByHQLWithPagingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginGetListByProperties(string properties, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListByProperties(properties, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndGetListByProperties(System.IAsyncResult result) {
            return base.Channel.EndGetListByProperties(result);
        }
        
        private System.IAsyncResult OnBeginGetListByProperties(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string properties = ((string)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginGetListByProperties(properties, callback, asyncState);
        }
        
        private object[] OnEndGetListByProperties(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndGetListByProperties(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListByPropertiesCompleted(object state) {
            if ((this.GetListByPropertiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListByPropertiesCompleted(this, new GetListByPropertiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListByPropertiesAsync(string properties) {
            this.GetListByPropertiesAsync(properties, null);
        }
        
        public void GetListByPropertiesAsync(string properties, object userState) {
            if ((this.onBeginGetListByPropertiesDelegate == null)) {
                this.onBeginGetListByPropertiesDelegate = new BeginOperationDelegate(this.OnBeginGetListByProperties);
            }
            if ((this.onEndGetListByPropertiesDelegate == null)) {
                this.onEndGetListByPropertiesDelegate = new EndOperationDelegate(this.OnEndGetListByProperties);
            }
            if ((this.onGetListByPropertiesCompletedDelegate == null)) {
                this.onGetListByPropertiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListByPropertiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetListByPropertiesDelegate, new object[] {
                        properties}, this.onEndGetListByPropertiesDelegate, this.onGetListByPropertiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoliceSMS.SMSRecordService.ISMSRecordService.BeginExport(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExport(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string PoliceSMS.SMSRecordService.ISMSRecordService.EndExport(System.IAsyncResult result) {
            return base.Channel.EndExport(result);
        }
        
        private System.IAsyncResult OnBeginExport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).BeginExport(query, callback, asyncState);
        }
        
        private object[] OnEndExport(System.IAsyncResult result) {
            string retVal = ((PoliceSMS.SMSRecordService.ISMSRecordService)(this)).EndExport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExportCompleted(object state) {
            if ((this.ExportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExportCompleted(this, new ExportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExportAsync(string query) {
            this.ExportAsync(query, null);
        }
        
        public void ExportAsync(string query, object userState) {
            if ((this.onBeginExportDelegate == null)) {
                this.onBeginExportDelegate = new BeginOperationDelegate(this.OnBeginExport);
            }
            if ((this.onEndExportDelegate == null)) {
                this.onEndExportDelegate = new EndOperationDelegate(this.OnEndExport);
            }
            if ((this.onExportCompletedDelegate == null)) {
                this.onExportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExportCompleted);
            }
            base.InvokeAsync(this.onBeginExportDelegate, new object[] {
                        query}, this.onEndExportDelegate, this.onExportCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PoliceSMS.SMSRecordService.ISMSRecordService CreateChannel() {
            return new SMSRecordServiceClientChannel(this);
        }
        
        private class SMSRecordServiceClientChannel : ChannelBase<PoliceSMS.SMSRecordService.ISMSRecordService>, PoliceSMS.SMSRecordService.ISMSRecordService {
            
            public SMSRecordServiceClientChannel(System.ServiceModel.ClientBase<PoliceSMS.SMSRecordService.ISMSRecordService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSaveOrUpdate(string json, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = json;
                System.IAsyncResult _result = base.BeginInvoke("SaveOrUpdate", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSaveOrUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("SaveOrUpdate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveList(string json, int cnt, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = json;
                _args[1] = cnt;
                System.IAsyncResult _result = base.BeginInvoke("SaveList", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSaveList(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("SaveList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteById(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("DeleteById", _args, callback, asyncState);
                return _result;
            }
            
            public string EndDeleteById(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("DeleteById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetById(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetById", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetById(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetByHql(string hql, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = hql;
                System.IAsyncResult _result = base.BeginInvoke("GetByHql", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetByHql(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetByHql", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetListByHQL(string hqlQuery, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = hqlQuery;
                System.IAsyncResult _result = base.BeginInvoke("GetListByHQL", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetListByHQL(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetListByHQL", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetListBySQL(string sql, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = sql;
                System.IAsyncResult _result = base.BeginInvoke("GetListBySQL", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetListBySQL(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetListBySQL", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetListByHQLWithPaging(string query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = query;
                System.IAsyncResult _result = base.BeginInvoke("GetListByHQLWithPaging", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetListByHQLWithPaging(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetListByHQLWithPaging", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetListByProperties(string properties, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = properties;
                System.IAsyncResult _result = base.BeginInvoke("GetListByProperties", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetListByProperties(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetListByProperties", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginExport(string query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = query;
                System.IAsyncResult _result = base.BeginInvoke("Export", _args, callback, asyncState);
                return _result;
            }
            
            public string EndExport(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Export", _args, result)));
                return _result;
            }
        }
    }
}
